# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wGDMeI5-F96YrLGsx4zBh6fT1pThfybx
"""

print("Hello world")